---

- name: 部署mysql
  hosts: init
  gather_facts: no
  roles:
    -  name: install_mysql
  tags: install_mysql


- name: 部署JDK11
  hosts: init
  gather_facts: no
  roles:
    -  name: install_jdk11
  tags: install_jdk11

- name: 部署ElasticSearch
  hosts: init
  gather_facts: no
  roles:
    -  name: install_ElasticSearch
  tags: install_ElasticSearch


- name: 部署KnowStreaming
  hosts: init
  gather_facts: no
  roles:
    -  name: install_KnowStreaming
  tags: install_KnowStreaming
